# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/zte/dana/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/zte/dana/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so

PRODUCT_COPY_FILES += \
  vendor/zte/dana/proprietary/bin/ccid_daemon:system/bin/ccid_daemon \
  vendor/zte/dana/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
  vendor/zte/dana/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
  vendor/zte/dana/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/zte/dana/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/zte/dana/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/zte/dana/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/zte/dana/proprietary/bin/thermald:system/bin/thermald \
  vendor/zte/dana/proprietary/bin/time_daemon:system/bin/time_daemon \
  vendor/zte/dana/proprietary/bin/cnd:system/bin/cnd \
  vendor/zte/dana/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
  vendor/zte/dana/proprietary/bin/port-bridge:system/bin/port-bridge \
  vendor/zte/dana/proprietary/bin/qmiproxy:system/bin/qmiproxy \
  vendor/zte/dana/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
  vendor/zte/dana/proprietary/bin/quipc_main:system/bin/quipc_main \
  vendor/zte/dana/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
  vendor/zte/dana/proprietary/bin/rild:system/bin/rild \
  vendor/zte/dana/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
  vendor/zte/dana/proprietary/bin/qseecomd:system/bin/qseecomd \
  vendor/zte/dana/proprietary/bin/btnvtool:system/bin/btnvtool \
  vendor/zte/dana/proprietary/bin/app6939:system/bin/app6939 \
  vendor/zte/dana/proprietary/bin/proximity.init:system/bin/proximity.init \
  vendor/zte/dana/proprietary/bin/pppd:system/bin/pppd \
  vendor/zte/dana/proprietary/bin/ppptunl:system/bin/ppptunl \
  vendor/zte/dana/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
  vendor/zte/dana/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
  vendor/zte/dana/proprietary/bin/fmconfig:system/bin/fmconfig \
  vendor/zte/dana/proprietary/bin/hostapd:system/bin/hostapd \
  vendor/zte/dana/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/zte/dana/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/zte/dana/proprietary/bin/akmd8962_new:system/bin/akmd8962_new \
  vendor/zte/dana/proprietary/lib/libUw.so:system/lib/libUw.so \
  vendor/zte/dana/proprietary/etc/ppp/ppptunl_up.sh:system/etc/ppp/ppptunl_up.sh \
  vendor/zte/dana/proprietary/etc/ppp/send_signal_to_ppptunl.sh:system/etc/ppp/send_signal_to_ppptunl.sh \
  vendor/zte/dana/proprietary/etc/ppp/set_pppd_apn.sh:system/etc/ppp/set_pppd_apn.sh \
  vendor/zte/dana/proprietary/etc/ppp/kill_pppd_and_ppptunl.sh:system/etc/ppp/kill_pppd_and_ppptunl.sh \
  vendor/zte/dana/proprietary/etc/ppp/chap-secrets:system/etc/ppp/chap-secrets \
  vendor/zte/dana/proprietary/etc/ppp/options:system/etc/ppp/options \
  vendor/zte/dana/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
  vendor/zte/dana/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
  vendor/zte/dana/proprietary/lib/libchromatix_vx6953_default_video.so:system/lib/libchromatix_vx6953_default_video.so \
  vendor/zte/dana/proprietary/lib/libchromatix_vx6953_preview.so:system/lib/libchromatix_vx6953_preview.so \
  vendor/zte/dana/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
  vendor/zte/dana/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/zte/dana/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
  vendor/zte/dana/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
  vendor/zte/dana/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
  vendor/zte/dana/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/zte/dana/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/zte/dana/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/zte/dana/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
  vendor/zte/dana/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
  vendor/zte/dana/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/zte/dana/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/zte/dana/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
  vendor/zte/dana/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
  vendor/zte/dana/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/zte/dana/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/zte/dana/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/zte/dana/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/zte/dana/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/zte/dana/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/zte/dana/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/zte/dana/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/zte/dana/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
  vendor/zte/dana/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
  vendor/zte/dana/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
  vendor/zte/dana/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
  vendor/zte/dana/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/zte/dana/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/zte/dana/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/zte/dana/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/zte/dana/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/zte/dana/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/zte/dana/proprietary/lib/libami.so:system/lib/libami.so \
  vendor/zte/dana/proprietary/lib/libami_sensor_mw.so:system/lib/libami_sensor_mw.so \
  vendor/zte/dana/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
  vendor/zte/dana/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
  vendor/zte/dana/proprietary/lib/libcneutils.so:system/lib/libcneutils.so \
  vendor/zte/dana/proprietary/lib/libxml.so:system/lib/libxml.so \
  vendor/zte/dana/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
  vendor/zte/dana/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so \
  vendor/zte/dana/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
  vendor/zte/dana/proprietary/lib/libmplmpu.so:system/lib/libmplmpu.so \
  vendor/zte/dana/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
  vendor/zte/dana/proprietary/lib/libmllite.so:system/lib/libmllite.so \
  vendor/zte/dana/proprietary/lib/libami.so:system/lib/libami.so \
  vendor/zte/dana/proprietary/lib/libakmd.so:system/lib/libakmd.so \
  vendor/zte/dana/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
  vendor/zte/dana/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
  vendor/zte/dana/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
  vendor/zte/dana/proprietary/framework/modemwarmup.jar:system/framework/modemwarmup.jar \
  vendor/zte/dana/proprietary/framework/qcnvitems.jar:system/framework/qcnvitems.jar \
  vendor/zte/dana/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
  vendor/zte/dana/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
  vendor/zte/dana/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml

#  vendor/zte/dana/proprietary/lib/hw/alsa.msm8960.so:system/lib/hw/alsa.msm8960.so \
#  vendor/zte/dana/proprietary/lib/libbluedroid.so:system/lib/libbluedroid.so \
#  vendor/zte/dana/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
